# Generated by Django 4.2.7 on 2023-11-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surfstore', '0002_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='prancha',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='0000000', max_length=20),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surfstore.cliente')),
                ('prancha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surfstore.prancha')),
            ],
        ),
    ]
