# Generated by Django 4.2.7 on 2023-11-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfstore', '0003_remove_cliente_prancha_cliente_telefone_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='', max_length=50),
        ),
    ]
